---
language: python
python: "2.7"
dist: trusty
sudo: required
services:
  - docker

env:
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1404-26"
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1604-25"
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1604-26"
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1604-27"
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1804-25"
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1804-26"
  - TEST_COMMAND="bundle exec kitchen test simple-ubuntu1804-27"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler

install:
  - sudo locale-gen en_US.UTF-8
  - sudo dpkg-reconfigure locales
  - bash ./test/ansible-setup.sh
  - bash ./test/setup_roles.sh
  - bundle install

script:
    - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 $TEST_COMMAND

after_success:
    - echo "Success"
