---

- name: common | Set default for 'CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS'
  set_fact:
    concourse_web_options_resource_type_defaults_file_path:
      CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS: '{{ concourseci_base_dir }}/resource-type-defaults.yml'
  when: "{{ concourseci_web_resource_type_defaults | dict2items | length > 0 }}"

- name: common | Combine dictionary options (web)
  set_fact:
    concourse_web_options_combined: >-
      {{
        concourse_web_options_default
        | combine(concourse_web_options_resource_type_defaults_file_path | default({}))
        | combine(concourse_web_options)
        | combine(concourse_facts_local_users)
        | combine(concourse_facts_main_users)
      }}
  when: "groups[concourseci_web_group] is defined and inventory_hostname in groups[concourseci_web_group]"

- name: common | Combine option for concourse_rbac
  set_fact:
    concourse_web_options_combined: '{{ concourse_web_options_combined | combine(concourse_web_rbac_config) }}'
  when: "groups[concourseci_web_group] is defined and inventory_hostname in groups[concourseci_web_group] and concourse_rbac is defined"

- name: common | Combine dictionary options (worker)
  set_fact:
    concourse_worker_options_combined: '{{ concourse_worker_options_default | combine(concourse_worker_options) }}'
  when: "groups[concourseci_worker_group] is defined and inventory_hostname in groups[concourseci_worker_group]"

- name: common | Ensure Concourse group exists
  group:
    name: '{{ concourseci_group }}'
    state: present

- name: common | Ensure Concourse user exists
  user:
    home: '{{ concourseci_base_dir }}'
    name: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    system: yes

- name: common | Ensure Concourse directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    mode: '0750'
  with_items:
    - '{{ concourseci_bin_dir }}'
    - '{{ concourseci_log_dir }}'
    - '{{ concourseci_archive_dir }}'
    - '{{ concourseci_archive_dir }}/{{ concourseci_binary_file }}'

- name: common | Ensure Concourse .ssh dir
  file:
    path: '{{ concourseci_ssh_dir }}'
    state: directory
    mode: '0750'
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
