---


- name: common | Combine dictionary options
  set_fact:
    concourse_web_options_combined: '{{ concourse_web_options_default | combine(concourse_web_options) | combine(concourse_facts_local_users) | combine(concourse_facts_main_users) }}'
    concourse_worker_options_combined: '{{ concourse_worker_options_default | combine(concourse_worker_options) }}'

- name: common | Ensure Concourse group exists
  group:
    name: '{{ concourseci_group }}'
    state: present

- name: common | Ensure Concourse user exists
  user:
    home: '{{ concourseci_base_dir }}'
    name: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    system: yes

- name: common | Ensure Concourse directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
    mode: '0750'
  with_items:
    - '{{ concourseci_bin_dir }}'
    - '{{ concourseci_log_dir }}'

- name: common | Ensure Concourse .ssh dir
  file:
    path: '{{ concourseci_ssh_dir }}'
    state: directory
    mode: '0750'
    owner: '{{ concourseci_user }}'
    group: '{{ concourseci_group }}'
